# Generated by Django 3.0.4 on 2020-03-09 21:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_snippet_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='tag',
            field=models.ManyToManyField(related_name='snippet_tag', to='users.Tag'),
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='user',
        ),
        migrations.AddField(
            model_name='snippet',
            name='user',
            field=models.ManyToManyField(related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
