# Generated by Django 3.0.4 on 2020-03-10 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200309_2154'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
