# Generated by Django 3.0.4 on 2020-03-10 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='tag',
            new_name='tags',
        ),
    ]
